apiVersion: v2
name: whitelabel
description: White-Label Customer On-Premises Installation Package
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: RuntimeAI TechOps
    email: techops@runtimeai.io
