apiVersion: v1
kind: Namespace
metadata:
  name: rt19
  labels:
    app.kubernetes.io/part-of: runtimeai
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: runtimeai-landing
  labels:
    app.kubernetes.io/part-of: runtimeai
    environment: production
