-- Seed File: 13_audit_logs.sql (SCHEMA-ALIGNED)
-- Purpose: Create 100 audit log entries across 5 tenants
-- Schema: id (SERIAL), tenant_id, actor, action, target, metadata (JSONB), created_at, processed

INSERT INTO audit_logs (tenant_id, actor, action, target, metadata, created_at, processed) VALUES
-- ACME Corp Audit Logs (20 entries)
('demo-acme-corp', 'admin@demo-acme-corp.local', 'agent.created', 'az-agent-acme-001', '{"agent_name": "DataCollector", "environment": "production"}', NOW() - INTERVAL '90 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'agent.updated', 'az-agent-acme-001', '{"field": "skills", "old_value": ["data_collection"], "new_value": ["data_collection", "reporting"]}', NOW() - INTERVAL '85 days', true),
('demo-acme-corp', 'operator@demo-acme-corp.local', 'tool.registered', 'tool-acme-postgres', '{"tool_name": "PostgresDB", "risk_tier": "HIGH"}', NOW() - INTERVAL '80 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'access_package.created', 'pkg-acme-prod-001', '{"package_name": "Production Agent Access", "approval_stages": 2}', NOW() - INTERVAL '75 days', true),
('demo-acme-corp', 'auditor@demo-acme-corp.local', 'access_review.started', 'campaign-acme-q1-2026', '{"campaign_name": "Q1 2026 Access Review", "scope": "all_agents"}', NOW() - INTERVAL '70 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'agent.quarantined', 'az-agent-acme-005', '{"reason": "policy_violation", "violation_type": "unauthorized_tool_access"}', NOW() - INTERVAL '65 days', true),
('demo-acme-corp', 'operator@demo-acme-corp.local', 'agent.restored', 'az-agent-acme-005', '{"reason": "violation_resolved", "approved_by": "admin@demo-acme-corp.local"}', NOW() - INTERVAL '60 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'policy.updated', 'policy-v1', '{"version": "v1", "changes": ["added_tool_restrictions", "updated_rate_limits"]}', NOW() - INTERVAL '55 days', true),
('demo-acme-corp', 'operator@demo-acme-corp.local', 'oauth.created', 'oauth-acme-salesforce', '{"provider": "Salesforce", "scopes": ["api.read", "data.write"]}', NOW() - INTERVAL '50 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'workflow.created', 'workflow-acme-autoprovision', '{"workflow_name": "Auto-Provision Access", "trigger": "agent_created"}', NOW() - INTERVAL '45 days', true),
('demo-acme-corp', 'operator@demo-acme-corp.local', 'agent.executed', 'az-agent-acme-001', '{"execution_time_ms": 1250, "success": true}', NOW() - INTERVAL '40 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'a2a_policy.created', 'a2a-acme-001', '{"source": "az-agent-acme-001", "target": "az-agent-acme-002", "max_requests_per_minute": 100}', NOW() - INTERVAL '35 days', true),
('demo-acme-corp', 'auditor@demo-acme-corp.local', 'compliance.framework_added', 'framework-soc2', '{"framework_name": "SOC 2 Type II", "controls_count": 64}', NOW() - INTERVAL '30 days', true),
('demo-acme-corp', 'operator@demo-acme-corp.local', 'quota.updated', 'quota-acme-agents', '{"quota_type": "agent_count", "old_limit": 50, "new_limit": 100}', NOW() - INTERVAL '25 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'agent.deleted', 'az-agent-acme-009', '{"reason": "decommissioned", "last_used": "2026-01-15"}', NOW() - INTERVAL '20 days', true),
('demo-acme-corp', 'operator@demo-acme-corp.local', 'tool.quarantined', 'tool-acme-stripe', '{"reason": "security_incident", "severity": "HIGH"}', NOW() - INTERVAL '15 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'tool.restored', 'tool-acme-stripe', '{"reason": "incident_resolved", "approved_by": "auditor@demo-acme-corp.local"}', NOW() - INTERVAL '10 days', true),
('demo-acme-corp', 'auditor@demo-acme-corp.local', 'access_review.completed', 'campaign-acme-q1-2026', '{"reviewed_count": 10, "revoked_count": 1, "approved_count": 9}', NOW() - INTERVAL '5 days', true),
('demo-acme-corp', 'operator@demo-acme-corp.local', 'agent.executed', 'az-agent-acme-002', '{"execution_time_ms": 850, "success": true}', NOW() - INTERVAL '2 days', true),
('demo-acme-corp', 'admin@demo-acme-corp.local', 'policy.published', 'policy-v2', '{"version": "v2", "effective_date": "2026-02-17"}', NOW() - INTERVAL '1 day', false),

-- TechStart Audit Logs (20 entries)
('demo-techstart', 'admin@demo-techstart.local', 'agent.created', 'az-agent-tech-001', '{"agent_name": "CustomerSupportBot", "environment": "production"}', NOW() - INTERVAL '60 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'tool.registered', 'tool-tech-linear', '{"tool_name": "Linear", "risk_tier": "LOW"}', NOW() - INTERVAL '55 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'access_package.created', 'pkg-tech-dev-001', '{"package_name": "Developer Standard Access", "approval_stages": 0}', NOW() - INTERVAL '50 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'agent.executed', 'az-agent-tech-001', '{"execution_time_ms": 450, "success": true}', NOW() - INTERVAL '45 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'oauth.created', 'oauth-tech-anthropic', '{"provider": "Anthropic", "scopes": ["messages.write"]}', NOW() - INTERVAL '40 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'workflow.created', 'workflow-tech-autoprovision', '{"workflow_name": "Auto-Provision Developer Access", "trigger": "agent_created"}', NOW() - INTERVAL '35 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'a2a_policy.created', 'a2a-tech-001', '{"source": "az-agent-tech-001", "target": "az-agent-tech-002", "max_requests_per_minute": 500}', NOW() - INTERVAL '30 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'agent.created', 'az-agent-tech-005', '{"agent_name": "CodeGenerator", "environment": "staging"}', NOW() - INTERVAL '25 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'quota.updated', 'quota-tech-agents', '{"quota_type": "agent_count", "old_limit": 25, "new_limit": 50}', NOW() - INTERVAL '20 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'agent.executed', 'az-agent-tech-005', '{"execution_time_ms": 1100, "success": true}', NOW() - INTERVAL '15 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'access_review.started', 'campaign-tech-monthly', '{"campaign_name": "Monthly Developer Access Review", "scope": "all_agents"}', NOW() - INTERVAL '10 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'tool.registered', 'tool-tech-vercel', '{"tool_name": "Vercel", "risk_tier": "MEDIUM"}', NOW() - INTERVAL '8 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'agent.updated', 'az-agent-tech-001', '{"field": "skills", "old_value": ["customer_support"], "new_value": ["customer_support", "ticket_routing"]}', NOW() - INTERVAL '6 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'agent.executed', 'az-agent-tech-002', '{"execution_time_ms": 650, "success": true}', NOW() - INTERVAL '4 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'workflow.executed', 'workflow-tech-autoprovision', '{"agent_id": "az-agent-tech-005", "access_granted": true}', NOW() - INTERVAL '3 days', true),
('demo-techstart', 'operator@demo-techstart.local', 'oauth.refreshed', 'oauth-tech-anthropic', '{"provider": "Anthropic", "expires_in_days": 90}', NOW() - INTERVAL '2 days', true),
('demo-techstart', 'admin@demo-techstart.local', 'access_review.completed', 'campaign-tech-monthly', '{"reviewed_count": 10, "revoked_count": 0, "approved_count": 10}', NOW() - INTERVAL '1 day', true),
('demo-techstart', 'operator@demo-techstart.local', 'agent.executed', 'az-agent-tech-003', '{"execution_time_ms": 520, "success": true}', NOW() - INTERVAL '12 hours', false),
('demo-techstart', 'admin@demo-techstart.local', 'policy.updated', 'policy-v1', '{"version": "v1", "changes": ["increased_rate_limits"]}', NOW() - INTERVAL '6 hours', false),
('demo-techstart', 'operator@demo-techstart.local', 'agent.created', 'az-agent-tech-010', '{"agent_name": "SlackIntegrator", "environment": "production"}', NOW() - INTERVAL '1 hour', false),

-- FinanceGlobal Audit Logs (20 entries)
('demo-financeglobal', 'admin@demo-financeglobal.local', 'agent.created', 'az-agent-finance-001', '{"agent_name": "TradingBot_Alpha", "environment": "production"}', NOW() - INTERVAL '120 days', true),
('demo-financeglobal', 'auditor@demo-financeglobal.local', 'compliance.framework_added', 'framework-sox', '{"framework_name": "SOX", "controls_count": 48}', NOW() - INTERVAL '115 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'access_package.created', 'pkg-finance-sox-001', '{"package_name": "SOX Database Access", "approval_stages": 2}', NOW() - INTERVAL '110 days', true),
('demo-financeglobal', 'operator@demo-financeglobal.local', 'tool.registered', 'tool-finance-postgres', '{"tool_name": "Trading Database", "risk_tier": "HIGH"}', NOW() - INTERVAL '105 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'agent.executed', 'az-agent-finance-001', '{"execution_time_ms": 2500, "success": true, "trades_executed": 15}', NOW() - INTERVAL '100 days', true),
('demo-financeglobal', 'auditor@demo-financeglobal.local', 'access_review.started', 'campaign-finance-sox-q1', '{"campaign_name": "SOX Database Access Review", "scope": "database_write"}', NOW() - INTERVAL '95 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'oauth.created', 'oauth-finance-stripe', '{"provider": "Stripe", "scopes": ["payment_intents.write"]}', NOW() - INTERVAL '90 days', true),
('demo-financeglobal', 'operator@demo-financeglobal.local', 'workflow.created', 'workflow-finance-sox-approval', '{"workflow_name": "SOX Database Access Approval", "trigger": "access_granted"}', NOW() - INTERVAL '85 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'a2a_policy.created', 'a2a-finance-001', '{"source": "az-agent-finance-001", "target": "az-agent-finance-002", "max_requests_per_minute": 25, "blocked": true}', NOW() - INTERVAL '80 days', true),
('demo-financeglobal', 'auditor@demo-financeglobal.local', 'compliance.framework_added', 'framework-pcidss', '{"framework_name": "PCI-DSS v4.0", "controls_count": 72}', NOW() - INTERVAL '75 days', true),
('demo-financeglobal', 'operator@demo-financeglobal.local', 'agent.executed', 'az-agent-finance-002', '{"execution_time_ms": 1800, "success": true}', NOW() - INTERVAL '70 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'quota.updated', 'quota-finance-agents', '{"quota_type": "agent_count", "old_limit": 100, "new_limit": 200}', NOW() - INTERVAL '65 days', true),
('demo-financeglobal', 'auditor@demo-financeglobal.local', 'access_review.completed', 'campaign-finance-sox-q1', '{"reviewed_count": 10, "revoked_count": 2, "approved_count": 8}', NOW() - INTERVAL '60 days', true),
('demo-financeglobal', 'operator@demo-financeglobal.local', 'tool.registered', 'tool-finance-bloomberg', '{"tool_name": "Bloomberg Terminal", "risk_tier": "MEDIUM"}', NOW() - INTERVAL '55 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'agent.quarantined', 'az-agent-finance-005', '{"reason": "suspicious_trading_pattern", "severity": "CRITICAL"}', NOW() - INTERVAL '50 days', true),
('demo-financeglobal', 'auditor@demo-financeglobal.local', 'incident.created', 'incident-finance-001', '{"type": "unauthorized_trade", "agent_id": "az-agent-finance-005", "amount_usd": 50000}', NOW() - INTERVAL '50 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'agent.restored', 'az-agent-finance-005', '{"reason": "false_positive", "approved_by": "cfo@demo-financeglobal.local"}', NOW() - INTERVAL '45 days', true),
('demo-financeglobal', 'operator@demo-financeglobal.local', 'workflow.executed', 'workflow-finance-sox-approval', '{"agent_id": "az-agent-finance-003", "approvals": ["admin", "auditor"]}', NOW() - INTERVAL '40 days', true),
('demo-financeglobal', 'admin@demo-financeglobal.local', 'policy.published', 'policy-v2', '{"version": "v2", "effective_date": "2026-02-01", "sox_compliant": true}', NOW() - INTERVAL '35 days', true),
('demo-financeglobal', 'auditor@demo-financeglobal.local', 'compliance.audit_completed', 'audit-sox-2026', '{"framework": "SOX", "findings_count": 0, "status": "passed"}', NOW() - INTERVAL '30 days', true),

-- HealthTech Audit Logs (20 entries)
('demo-healthtech', 'admin@demo-healthtech.local', 'agent.created', 'az-agent-health-001', '{"agent_name": "PHI_AnalysisBot", "environment": "production"}', NOW() - INTERVAL '100 days', true),
('demo-healthtech', 'auditor@demo-healthtech.local', 'compliance.framework_added', 'framework-hipaa', '{"framework_name": "HIPAA Security Rule", "controls_count": 54}', NOW() - INTERVAL '95 days', true),
('demo-healthtech', 'admin@demo-healthtech.local', 'access_package.created', 'pkg-health-phi-001', '{"package_name": "HIPAA PHI Access", "approval_stages": 2}', NOW() - INTERVAL '90 days', true),
('demo-healthtech', 'operator@demo-healthtech.local', 'tool.registered', 'tool-health-epic', '{"tool_name": "Epic EHR", "risk_tier": "HIGH"}', NOW() - INTERVAL '85 days', true),
('demo-healthtech', 'admin@demo-healthtech.local', 'oauth.created', 'oauth-health-epic', '{"provider": "Epic", "scopes": ["patient/*.read", "observation/*.read"]}', NOW() - INTERVAL '80 days', true),
('demo-healthtech', 'auditor@demo-healthtech.local', 'access_review.started', 'campaign-health-hipaa-monthly', '{"campaign_name": "HIPAA PHI Access Review", "scope": "access_phi"}', NOW() - INTERVAL '75 days', true),
('demo-healthtech', 'operator@demo-healthtech.local', 'workflow.created', 'workflow-health-phi-approval', '{"workflow_name": "HIPAA PHI Access Approval", "trigger": "access_granted"}', NOW() - INTERVAL '70 days', true),
('demo-healthtech', 'admin@demo-healthtech.local', 'a2a_policy.created', 'a2a-health-001', '{"source": "az-agent-health-001", "target": "az-agent-health-002", "max_requests_per_minute": 10}', NOW() - INTERVAL '65 days', true),
('demo-healthtech', 'operator@demo-healthtech.local', 'agent.executed', 'az-agent-health-001', '{"execution_time_ms": 3200, "success": true, "phi_records_accessed": 25}', NOW() - INTERVAL '60 days', true),
('demo-healthtech', 'auditor@demo-healthtech.local', 'compliance.framework_added', 'framework-hitrust', '{"framework_name": "HITRUST CSF v11", "controls_count": 156}', NOW() - INTERVAL '55 days', true),
('demo-healthtech', 'admin@demo-healthtech.local', 'oauth.revoked', 'oauth-health-openai', '{"provider": "OpenAI", "reason": "no_baa", "severity": "HIGH"}', NOW() - INTERVAL '50 days', true),
('demo-healthtech', 'auditor@demo-healthtech.local', 'incident.created', 'incident-health-001', '{"type": "phi_access_without_baa", "oauth_id": "oauth-health-openai"}', NOW() - INTERVAL '50 days', true),
('demo-healthtech', 'operator@demo-healthtech.local', 'workflow.executed', 'workflow-health-phi-approval', '{"agent_id": "az-agent-health-003", "approvals": ["admin", "privacy-officer"]}', NOW() - INTERVAL '45 days', true),
('demo-healthtech', 'admin@demo-healthtech.local', 'quota.updated', 'quota-health-storage', '{"quota_type": "storage_gb", "old_limit": 1000, "new_limit": 2000}', NOW() - INTERVAL '40 days', true),
('demo-healthtech', 'auditor@demo-healthtech.local', 'access_review.completed', 'campaign-health-hipaa-monthly', '{"reviewed_count": 10, "revoked_count": 1, "approved_count": 9}', NOW() - INTERVAL '35 days', true),
('demo-healthtech', 'operator@demo-healthtech.local', 'agent.executed', 'az-agent-health-002', '{"execution_time_ms": 2800, "success": true, "phi_records_accessed": 18}', NOW() - INTERVAL '30 days', true),
('demo-healthtech', 'admin@demo-healthtech.local', 'policy.updated', 'policy-v1', '{"version": "v1", "changes": ["added_phi_access_controls", "updated_baa_requirements"]}', NOW() - INTERVAL '25 days', true),
('demo-healthtech', 'auditor@demo-healthtech.local', 'compliance.audit_completed', 'audit-hipaa-2026', '{"framework": "HIPAA", "findings_count": 1, "status": "conditional_pass"}', NOW() - INTERVAL '20 days', true),
('demo-healthtech', 'operator@demo-healthtech.local', 'tool.registered', 'tool-health-cerner', '{"tool_name": "Cerner EHR", "risk_tier": "HIGH"}', NOW() - INTERVAL '15 days', true),
('demo-healthtech', 'admin@demo-healthtech.local', 'agent.created', 'az-agent-health-010', '{"agent_name": "DiagnosisAssistant", "environment": "production"}', NOW() - INTERVAL '10 days', true),

-- DevShop Audit Logs (20 entries)
('demo-devshop', 'admin@demo-devshop.local', 'agent.created', 'az-agent-devops-001', '{"agent_name": "CI_CD_Orchestrator", "environment": "staging"}', NOW() - INTERVAL '45 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'tool.registered', 'tool-devops-github', '{"tool_name": "GitHub", "risk_tier": "MEDIUM"}', NOW() - INTERVAL '40 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'access_package.created', 'pkg-devops-cicd-001', '{"package_name": "CI/CD Agent Access", "approval_stages": 1}', NOW() - INTERVAL '35 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'oauth.created', 'oauth-devops-github', '{"provider": "GitHub", "scopes": ["repo.write", "actions.write"]}', NOW() - INTERVAL '30 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'workflow.created', 'workflow-devops-autoprovision', '{"workflow_name": "CI/CD Auto-Provisioning", "trigger": "agent_created"}', NOW() - INTERVAL '25 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'agent.executed', 'az-agent-devops-001', '{"execution_time_ms": 5500, "success": true, "deployments": 3}', NOW() - INTERVAL '20 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'a2a_policy.created', 'a2a-devops-001', '{"source": "az-agent-devops-001", "target": "az-agent-devops-002", "max_requests_per_minute": 1000}', NOW() - INTERVAL '18 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'tool.registered', 'tool-devops-docker', '{"tool_name": "Docker Hub", "risk_tier": "LOW"}', NOW() - INTERVAL '16 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'quota.updated', 'quota-devops-agents', '{"quota_type": "agent_count", "old_limit": 200, "new_limit": 500}', NOW() - INTERVAL '14 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'workflow.executed', 'workflow-devops-autoprovision', '{"agent_id": "az-agent-devops-005", "access_granted": true}', NOW() - INTERVAL '12 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'agent.created', 'az-agent-devops-005', '{"agent_name": "LoadTester", "environment": "staging"}', NOW() - INTERVAL '12 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'agent.executed', 'az-agent-devops-005', '{"execution_time_ms": 45000, "success": true, "requests_sent": 10000}', NOW() - INTERVAL '10 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'access_review.started', 'campaign-devops-quarterly', '{"campaign_name": "Quarterly CI/CD Access Review", "scope": "ci-cd"}', NOW() - INTERVAL '8 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'tool.registered', 'tool-devops-vercel', '{"tool_name": "Vercel", "risk_tier": "LOW"}', NOW() - INTERVAL '6 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'workflow.created', 'workflow-devops-promotion', '{"workflow_name": "Staging Promotion", "trigger": "agent_approved"}', NOW() - INTERVAL '5 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'agent.executed', 'az-agent-devops-002', '{"execution_time_ms": 3200, "success": true}', NOW() - INTERVAL '4 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'access_review.completed', 'campaign-devops-quarterly', '{"reviewed_count": 10, "revoked_count": 0, "approved_count": 10}', NOW() - INTERVAL '3 days', true),
('demo-devshop', 'operator@demo-devshop.local', 'oauth.refreshed', 'oauth-devops-github', '{"provider": "GitHub", "expires_in_days": 90}', NOW() - INTERVAL '2 days', true),
('demo-devshop', 'admin@demo-devshop.local', 'policy.updated', 'policy-v1', '{"version": "v1", "changes": ["increased_a2a_rate_limits"]}', NOW() - INTERVAL '1 day', true),
('demo-devshop', 'operator@demo-devshop.local', 'agent.created', 'az-agent-devops-010', '{"agent_name": "InfraProvisioner", "environment": "staging"}', NOW() - INTERVAL '6 hours', false)
ON CONFLICT DO NOTHING;

-- Summary: 100 audit log entries (20 per tenant)
-- Actions covered: agent operations, tool management, access control, compliance, OAuth, workflows, A2A policies, quotas
-- Time range: 120 days ago to 1 hour ago
-- Processed: 95 true, 5 false (recent events)
