-- seed_500_servers.sql
-- 500+ MCP Server Integration Catalog for RuntimeAI
-- Generated: 2026-02-22
-- Run: psql $DATABASE_URL < deployment/seed/seed_500_servers.sql

INSERT INTO integration_catalog (name, display_name, category, description, mcp_server_image, tier) VALUES
('okta', 'Okta', 'identity', 'Okta MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-okta:1.0.0', 'core'),
('azure-ad', 'Azure Ad', 'identity', 'Azure Ad MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-ad:1.0.0', 'core'),
('ping-identity', 'Ping Identity', 'identity', 'Ping Identity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ping-identity:1.0.0', 'core'),
('onelogin', 'Onelogin', 'identity', 'Onelogin MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-onelogin:1.0.0', 'core'),
('auth0', 'Auth0', 'identity', 'Auth0 MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-auth0:1.0.0', 'core'),
('jumpcloud', 'Jumpcloud', 'identity', 'Jumpcloud MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-jumpcloud:1.0.0', 'core'),
('cyberark-idaptive', 'Cyberark Idaptive', 'identity', 'Cyberark Idaptive MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cyberark-idaptive:1.0.0', 'core'),
('sailpoint-idn', 'Sailpoint Idn', 'identity', 'Sailpoint Idn MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sailpoint-idn:1.0.0', 'core'),
('saviynt', 'Saviynt', 'identity', 'Saviynt MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-saviynt:1.0.0', 'core'),
('forgerock', 'Forgerock', 'identity', 'Forgerock MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-forgerock:1.0.0', 'core'),
('keycloak', 'Keycloak', 'identity', 'Keycloak MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-keycloak:1.0.0', 'core'),
('duo-security', 'Duo Security', 'identity', 'Duo Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-duo-security:1.0.0', 'core'),
('beyond-identity', 'Beyond Identity', 'identity', 'Beyond Identity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-beyond-identity:1.0.0', 'core'),
('stytch', 'Stytch', 'identity', 'Stytch MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-stytch:1.0.0', 'core'),
('descope', 'Descope', 'identity', 'Descope MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-descope:1.0.0', 'core'),
('frontegg', 'Frontegg', 'identity', 'Frontegg MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-frontegg:1.0.0', 'core'),
('clerk', 'Clerk', 'identity', 'Clerk MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-clerk:1.0.0', 'core'),
('propel-auth', 'Propel Auth', 'identity', 'Propel Auth MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-propel-auth:1.0.0', 'core'),
('fusionauth', 'Fusionauth', 'identity', 'Fusionauth MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-fusionauth:1.0.0', 'core'),
('gluu', 'Gluu', 'identity', 'Gluu MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gluu:1.0.0', 'core'),
('workspace-one', 'Workspace One', 'identity', 'Workspace One MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-workspace-one:1.0.0', 'core'),
('sso-circle', 'Sso Circle', 'identity', 'Sso Circle MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sso-circle:1.0.0', 'core'),
('openiam', 'Openiam', 'identity', 'Openiam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-openiam:1.0.0', 'core'),
('trusona', 'Trusona', 'identity', 'Trusona MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-trusona:1.0.0', 'core'),
('loginradius', 'Loginradius', 'identity', 'Loginradius MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-loginradius:1.0.0', 'core'),
('centrify', 'Centrify', 'identity', 'Centrify MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-centrify:1.0.0', 'core'),
('thales-safenet', 'Thales Safenet', 'identity', 'Thales Safenet MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-thales-safenet:1.0.0', 'core'),
('secureauth', 'Secureauth', 'identity', 'Secureauth MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-secureauth:1.0.0', 'core'),
('transmit-security', 'Transmit Security', 'identity', 'Transmit Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-transmit-security:1.0.0', 'core'),
('hypr', 'Hypr', 'identity', 'Hypr MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hypr:1.0.0', 'core'),
('beyond-trust', 'Beyond Trust', 'identity', 'Beyond Trust MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-beyond-trust:1.0.0', 'extended'),
('aws-iam', 'Aws Iam', 'cloud', 'Aws Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-iam:1.0.0', 'extended'),
('gcp-iam', 'Gcp Iam', 'cloud', 'Gcp Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-iam:1.0.0', 'extended'),
('azure-rbac', 'Azure Rbac', 'cloud', 'Azure Rbac MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-rbac:1.0.0', 'extended'),
('oracle-cloud-iam', 'Oracle Cloud Iam', 'cloud', 'Oracle Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-oracle-cloud-iam:1.0.0', 'extended'),
('ibm-cloud-iam', 'Ibm Cloud Iam', 'cloud', 'Ibm Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ibm-cloud-iam:1.0.0', 'extended'),
('digitalocean-iam', 'Digitalocean Iam', 'cloud', 'Digitalocean Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-digitalocean-iam:1.0.0', 'extended'),
('linode-iam', 'Linode Iam', 'cloud', 'Linode Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-linode-iam:1.0.0', 'extended'),
('vultr-iam', 'Vultr Iam', 'cloud', 'Vultr Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-vultr-iam:1.0.0', 'extended'),
('hetzner-iam', 'Hetzner Iam', 'cloud', 'Hetzner Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hetzner-iam:1.0.0', 'extended'),
('scaleway-iam', 'Scaleway Iam', 'cloud', 'Scaleway Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-scaleway-iam:1.0.0', 'extended'),
('ovhcloud-iam', 'Ovhcloud Iam', 'cloud', 'Ovhcloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ovhcloud-iam:1.0.0', 'extended'),
('alibaba-cloud-iam', 'Alibaba Cloud Iam', 'cloud', 'Alibaba Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-alibaba-cloud-iam:1.0.0', 'extended'),
('tencent-cloud-iam', 'Tencent Cloud Iam', 'cloud', 'Tencent Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tencent-cloud-iam:1.0.0', 'extended'),
('huawei-cloud-iam', 'Huawei Cloud Iam', 'cloud', 'Huawei Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-huawei-cloud-iam:1.0.0', 'extended'),
('naver-cloud-iam', 'Naver Cloud Iam', 'cloud', 'Naver Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-naver-cloud-iam:1.0.0', 'extended'),
('kakao-cloud-iam', 'Kakao Cloud Iam', 'cloud', 'Kakao Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-kakao-cloud-iam:1.0.0', 'extended'),
('nifcloud-iam', 'Nifcloud Iam', 'cloud', 'Nifcloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-nifcloud-iam:1.0.0', 'extended'),
('sakura-cloud-iam', 'Sakura Cloud Iam', 'cloud', 'Sakura Cloud Iam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sakura-cloud-iam:1.0.0', 'extended'),
('aws-sso', 'Aws Sso', 'cloud', 'Aws Sso MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-sso:1.0.0', 'extended'),
('gcp-workload-identity', 'Gcp Workload Identity', 'cloud', 'Gcp Workload Identity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-workload-identity:1.0.0', 'extended'),
('azure-managed-identity', 'Azure Managed Identity', 'cloud', 'Azure Managed Identity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-managed-identity:1.0.0', 'extended'),
('aws-organizations', 'Aws Organizations', 'cloud', 'Aws Organizations MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-organizations:1.0.0', 'extended'),
('gcp-resource-manager', 'Gcp Resource Manager', 'cloud', 'Gcp Resource Manager MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-resource-manager:1.0.0', 'extended'),
('azure-management-groups', 'Azure Management Groups', 'cloud', 'Azure Management Groups MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-management-groups:1.0.0', 'extended'),
('cloudflare-access', 'Cloudflare Access', 'cloud', 'Cloudflare Access MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cloudflare-access:1.0.0', 'extended'),
('github', 'Github', 'devops', 'Github MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-github:1.0.0', 'extended'),
('gitlab', 'Gitlab', 'devops', 'Gitlab MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gitlab:1.0.0', 'extended'),
('bitbucket', 'Bitbucket', 'devops', 'Bitbucket MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bitbucket:1.0.0', 'extended'),
('jenkins', 'Jenkins', 'devops', 'Jenkins MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-jenkins:1.0.0', 'extended'),
('circleci', 'Circleci', 'devops', 'Circleci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-circleci:1.0.0', 'extended'),
('travis-ci', 'Travis Ci', 'devops', 'Travis Ci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-travis-ci:1.0.0', 'extended'),
('argo-cd', 'Argo Cd', 'devops', 'Argo Cd MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-argo-cd:1.0.0', 'extended'),
('flux-cd', 'Flux Cd', 'devops', 'Flux Cd MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-flux-cd:1.0.0', 'extended'),
('tekton', 'Tekton', 'devops', 'Tekton MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tekton:1.0.0', 'extended'),
('drone-ci', 'Drone Ci', 'devops', 'Drone Ci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-drone-ci:1.0.0', 'extended'),
('buddy-works', 'Buddy Works', 'devops', 'Buddy Works MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-buddy-works:1.0.0', 'extended'),
('buildkite', 'Buildkite', 'devops', 'Buildkite MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-buildkite:1.0.0', 'extended'),
('semaphore-ci', 'Semaphore Ci', 'devops', 'Semaphore Ci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-semaphore-ci:1.0.0', 'extended'),
('codefresh', 'Codefresh', 'devops', 'Codefresh MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-codefresh:1.0.0', 'extended'),
('harness-ci', 'Harness Ci', 'devops', 'Harness Ci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-harness-ci:1.0.0', 'extended'),
('bamboo', 'Bamboo', 'devops', 'Bamboo MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bamboo:1.0.0', 'extended'),
('teamcity', 'Teamcity', 'devops', 'Teamcity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-teamcity:1.0.0', 'extended'),
('azure-devops', 'Azure Devops', 'devops', 'Azure Devops MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-devops:1.0.0', 'extended'),
('aws-codepipeline', 'Aws Codepipeline', 'devops', 'Aws Codepipeline MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-codepipeline:1.0.0', 'extended'),
('gcp-cloud-build', 'Gcp Cloud Build', 'devops', 'Gcp Cloud Build MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-cloud-build:1.0.0', 'extended'),
('github-actions', 'Github Actions', 'devops', 'Github Actions MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-github-actions:1.0.0', 'extended'),
('gitlab-ci', 'Gitlab Ci', 'devops', 'Gitlab Ci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gitlab-ci:1.0.0', 'extended'),
('spacelift', 'Spacelift', 'devops', 'Spacelift MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-spacelift:1.0.0', 'extended'),
('env0', 'Env0', 'devops', 'Env0 MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-env0:1.0.0', 'extended'),
('pulumi-cloud', 'Pulumi Cloud', 'devops', 'Pulumi Cloud MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-pulumi-cloud:1.0.0', 'extended'),
('terraform-cloud', 'Terraform Cloud', 'devops', 'Terraform Cloud MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-terraform-cloud:1.0.0', 'extended'),
('atlantis', 'Atlantis', 'devops', 'Atlantis MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-atlantis:1.0.0', 'extended'),
('crossplane', 'Crossplane', 'devops', 'Crossplane MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-crossplane:1.0.0', 'extended'),
('waypoint', 'Waypoint', 'devops', 'Waypoint MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-waypoint:1.0.0', 'extended'),
('nomad', 'Nomad', 'devops', 'Nomad MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-nomad:1.0.0', 'extended'),
('spinnaker', 'Spinnaker', 'devops', 'Spinnaker MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-spinnaker:1.0.0', 'extended'),
('octopus-deploy', 'Octopus Deploy', 'devops', 'Octopus Deploy MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-octopus-deploy:1.0.0', 'extended'),
('rundeck', 'Rundeck', 'devops', 'Rundeck MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-rundeck:1.0.0', 'extended'),
('ansible-tower', 'Ansible Tower', 'devops', 'Ansible Tower MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ansible-tower:1.0.0', 'extended'),
('chef-infra', 'Chef Infra', 'devops', 'Chef Infra MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-chef-infra:1.0.0', 'extended'),
('puppet-enterprise', 'Puppet Enterprise', 'devops', 'Puppet Enterprise MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-puppet-enterprise:1.0.0', 'extended'),
('salt-project', 'Salt Project', 'devops', 'Salt Project MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-salt-project:1.0.0', 'extended'),
('zuul-ci', 'Zuul Ci', 'devops', 'Zuul Ci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zuul-ci:1.0.0', 'extended'),
('concourse-ci', 'Concourse Ci', 'devops', 'Concourse Ci MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-concourse-ci:1.0.0', 'extended'),
('splunk', 'Splunk', 'security', 'Splunk MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-splunk:1.0.0', 'extended'),
('crowdstrike', 'Crowdstrike', 'security', 'Crowdstrike MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-crowdstrike:1.0.0', 'extended'),
('sentinelone', 'Sentinelone', 'security', 'Sentinelone MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sentinelone:1.0.0', 'extended'),
('wiz', 'Wiz', 'security', 'Wiz MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-wiz:1.0.0', 'extended'),
('snyk', 'Snyk', 'security', 'Snyk MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-snyk:1.0.0', 'extended'),
('lacework', 'Lacework', 'security', 'Lacework MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-lacework:1.0.0', 'community'),
('qualys', 'Qualys', 'security', 'Qualys MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-qualys:1.0.0', 'community'),
('tenable', 'Tenable', 'security', 'Tenable MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tenable:1.0.0', 'community'),
('rapid7', 'Rapid7', 'security', 'Rapid7 MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-rapid7:1.0.0', 'community'),
('palo-alto-cortex', 'Palo Alto Cortex', 'security', 'Palo Alto Cortex MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-palo-alto-cortex:1.0.0', 'community'),
('sumo-logic', 'Sumo Logic', 'security', 'Sumo Logic MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sumo-logic:1.0.0', 'community'),
('elastic-security', 'Elastic Security', 'security', 'Elastic Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-elastic-security:1.0.0', 'community'),
('datadog-security', 'Datadog Security', 'security', 'Datadog Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-datadog-security:1.0.0', 'community'),
('carbon-black', 'Carbon Black', 'security', 'Carbon Black MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-carbon-black:1.0.0', 'community'),
('cybereason', 'Cybereason', 'security', 'Cybereason MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cybereason:1.0.0', 'community'),
('darktrace', 'Darktrace', 'security', 'Darktrace MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-darktrace:1.0.0', 'community'),
('vectra-ai', 'Vectra Ai', 'security', 'Vectra Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-vectra-ai:1.0.0', 'community'),
('exabeam', 'Exabeam', 'security', 'Exabeam MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-exabeam:1.0.0', 'community'),
('securonix', 'Securonix', 'security', 'Securonix MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-securonix:1.0.0', 'community'),
('logrhythm', 'Logrhythm', 'security', 'Logrhythm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-logrhythm:1.0.0', 'community'),
('ibm-qradar', 'Ibm Qradar', 'security', 'Ibm Qradar MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ibm-qradar:1.0.0', 'community'),
('arc-sight', 'Arc Sight', 'security', 'Arc Sight MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-arc-sight:1.0.0', 'community'),
('alien-vault', 'Alien Vault', 'security', 'Alien Vault MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-alien-vault:1.0.0', 'community'),
('devo-security', 'Devo Security', 'security', 'Devo Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-devo-security:1.0.0', 'community'),
('chronicle-security', 'Chronicle Security', 'security', 'Chronicle Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-chronicle-security:1.0.0', 'community'),
('microsoft-sentinel', 'Microsoft Sentinel', 'security', 'Microsoft Sentinel MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-microsoft-sentinel:1.0.0', 'community'),
('amazon-guardduty', 'Amazon Guardduty', 'security', 'Amazon Guardduty MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-amazon-guardduty:1.0.0', 'community'),
('prisma-cloud', 'Prisma Cloud', 'security', 'Prisma Cloud MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-prisma-cloud:1.0.0', 'community'),
('orca-security', 'Orca Security', 'security', 'Orca Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-orca-security:1.0.0', 'community'),
('aqua-security', 'Aqua Security', 'security', 'Aqua Security MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aqua-security:1.0.0', 'community'),
('sysdig-secure', 'Sysdig Secure', 'security', 'Sysdig Secure MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sysdig-secure:1.0.0', 'community'),
('twistlock', 'Twistlock', 'security', 'Twistlock MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-twistlock:1.0.0', 'community'),
('falco', 'Falco', 'security', 'Falco MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-falco:1.0.0', 'community'),
('trivy', 'Trivy', 'security', 'Trivy MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-trivy:1.0.0', 'community'),
('grype', 'Grype', 'security', 'Grype MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-grype:1.0.0', 'community'),
('clair', 'Clair', 'security', 'Clair MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-clair:1.0.0', 'community'),
('anchore', 'Anchore', 'security', 'Anchore MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-anchore:1.0.0', 'community'),
('checkov', 'Checkov', 'security', 'Checkov MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-checkov:1.0.0', 'community'),
('tfsec', 'Tfsec', 'security', 'Tfsec MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tfsec:1.0.0', 'community'),
('slack', 'Slack', 'saas', 'Slack MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-slack:1.0.0', 'community'),
('microsoft-teams', 'Microsoft Teams', 'saas', 'Microsoft Teams MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-microsoft-teams:1.0.0', 'community'),
('jira', 'Jira', 'saas', 'Jira MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-jira:1.0.0', 'community'),
('confluence', 'Confluence', 'saas', 'Confluence MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-confluence:1.0.0', 'community'),
('notion', 'Notion', 'saas', 'Notion MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-notion:1.0.0', 'community'),
('monday', 'Monday', 'saas', 'Monday MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-monday:1.0.0', 'community'),
('asana', 'Asana', 'saas', 'Asana MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-asana:1.0.0', 'community'),
('trello', 'Trello', 'saas', 'Trello MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-trello:1.0.0', 'community'),
('clickup', 'Clickup', 'saas', 'Clickup MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-clickup:1.0.0', 'community'),
('linear', 'Linear', 'saas', 'Linear MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-linear:1.0.0', 'community'),
('basecamp', 'Basecamp', 'saas', 'Basecamp MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-basecamp:1.0.0', 'community'),
('todoist', 'Todoist', 'saas', 'Todoist MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-todoist:1.0.0', 'community'),
('smartsheet', 'Smartsheet', 'saas', 'Smartsheet MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-smartsheet:1.0.0', 'community'),
('airtable', 'Airtable', 'saas', 'Airtable MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-airtable:1.0.0', 'community'),
('coda', 'Coda', 'saas', 'Coda MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-coda:1.0.0', 'community'),
('fibery', 'Fibery', 'saas', 'Fibery MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-fibery:1.0.0', 'community'),
('height', 'Height', 'saas', 'Height MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-height:1.0.0', 'community'),
('hive', 'Hive', 'saas', 'Hive MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hive:1.0.0', 'community'),
('wrike', 'Wrike', 'saas', 'Wrike MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-wrike:1.0.0', 'community'),
('zoho-projects', 'Zoho Projects', 'saas', 'Zoho Projects MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zoho-projects:1.0.0', 'community'),
('google-workspace', 'Google Workspace', 'saas', 'Google Workspace MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-google-workspace:1.0.0', 'community'),
('microsoft-365', 'Microsoft 365', 'saas', 'Microsoft 365 MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-microsoft-365:1.0.0', 'community'),
('dropbox-business', 'Dropbox Business', 'saas', 'Dropbox Business MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-dropbox-business:1.0.0', 'community'),
('box', 'Box', 'saas', 'Box MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-box:1.0.0', 'community'),
('docusign', 'Docusign', 'saas', 'Docusign MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-docusign:1.0.0', 'community'),
('adobe-sign', 'Adobe Sign', 'saas', 'Adobe Sign MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-adobe-sign:1.0.0', 'community'),
('pandadoc', 'Pandadoc', 'saas', 'Pandadoc MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-pandadoc:1.0.0', 'community'),
('hellosign', 'Hellosign', 'saas', 'Hellosign MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hellosign:1.0.0', 'community'),
('signrequest', 'Signrequest', 'saas', 'Signrequest MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-signrequest:1.0.0', 'community'),
('yousign', 'Yousign', 'saas', 'Yousign MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-yousign:1.0.0', 'community'),
('concord', 'Concord', 'saas', 'Concord MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-concord:1.0.0', 'community'),
('ironclad', 'Ironclad', 'saas', 'Ironclad MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ironclad:1.0.0', 'community'),
('snowflake', 'Snowflake', 'database', 'Snowflake MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-snowflake:1.0.0', 'community'),
('databricks', 'Databricks', 'database', 'Databricks MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-databricks:1.0.0', 'community'),
('bigquery', 'Bigquery', 'database', 'Bigquery MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bigquery:1.0.0', 'community'),
('redshift', 'Redshift', 'database', 'Redshift MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-redshift:1.0.0', 'community'),
('mongodb', 'Mongodb', 'database', 'Mongodb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mongodb:1.0.0', 'community'),
('postgresql', 'Postgresql', 'database', 'Postgresql MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-postgresql:1.0.0', 'community'),
('mysql', 'Mysql', 'database', 'Mysql MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mysql:1.0.0', 'community'),
('mariadb', 'Mariadb', 'database', 'Mariadb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mariadb:1.0.0', 'community'),
('cockroachdb', 'Cockroachdb', 'database', 'Cockroachdb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cockroachdb:1.0.0', 'community'),
('yugabyte', 'Yugabyte', 'database', 'Yugabyte MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-yugabyte:1.0.0', 'community'),
('tidb', 'Tidb', 'database', 'Tidb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tidb:1.0.0', 'community'),
('planetscale', 'Planetscale', 'database', 'Planetscale MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-planetscale:1.0.0', 'community'),
('neon', 'Neon', 'database', 'Neon MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-neon:1.0.0', 'community'),
('supabase', 'Supabase', 'database', 'Supabase MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-supabase:1.0.0', 'community'),
('fauna', 'Fauna', 'database', 'Fauna MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-fauna:1.0.0', 'community'),
('dynamodb', 'Dynamodb', 'database', 'Dynamodb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-dynamodb:1.0.0', 'community'),
('cosmos-db', 'Cosmos Db', 'database', 'Cosmos Db MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cosmos-db:1.0.0', 'community'),
('firestore', 'Firestore', 'database', 'Firestore MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-firestore:1.0.0', 'community'),
('cassandra', 'Cassandra', 'database', 'Cassandra MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cassandra:1.0.0', 'community'),
('scylla', 'Scylla', 'database', 'Scylla MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-scylla:1.0.0', 'community'),
('clickhouse', 'Clickhouse', 'database', 'Clickhouse MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-clickhouse:1.0.0', 'community'),
('timescale', 'Timescale', 'database', 'Timescale MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-timescale:1.0.0', 'community'),
('influxdb', 'Influxdb', 'database', 'Influxdb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-influxdb:1.0.0', 'community'),
('questdb', 'Questdb', 'database', 'Questdb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-questdb:1.0.0', 'community'),
('duckdb', 'Duckdb', 'database', 'Duckdb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-duckdb:1.0.0', 'community'),
('motherduck', 'Motherduck', 'database', 'Motherduck MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-motherduck:1.0.0', 'community'),
('singlestore', 'Singlestore', 'database', 'Singlestore MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-singlestore:1.0.0', 'community'),
('memgraph', 'Memgraph', 'database', 'Memgraph MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-memgraph:1.0.0', 'community'),
('neo4j', 'Neo4j', 'database', 'Neo4j MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-neo4j:1.0.0', 'community'),
('arangodb', 'Arangodb', 'database', 'Arangodb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-arangodb:1.0.0', 'community'),
('dgraph', 'Dgraph', 'database', 'Dgraph MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-dgraph:1.0.0', 'community'),
('cloudflare', 'Cloudflare', 'networking', 'Cloudflare MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cloudflare:1.0.0', 'community'),
('akamai', 'Akamai', 'networking', 'Akamai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-akamai:1.0.0', 'community'),
('f5-bigip', 'F5 Bigip', 'networking', 'F5 Bigip MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-f5-bigip:1.0.0', 'community'),
('palo-alto', 'Palo Alto', 'networking', 'Palo Alto MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-palo-alto:1.0.0', 'community'),
('fortinet', 'Fortinet', 'networking', 'Fortinet MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-fortinet:1.0.0', 'community'),
('zscaler', 'Zscaler', 'networking', 'Zscaler MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zscaler:1.0.0', 'community'),
('netskope', 'Netskope', 'networking', 'Netskope MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-netskope:1.0.0', 'community'),
('cisco-meraki', 'Cisco Meraki', 'networking', 'Cisco Meraki MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cisco-meraki:1.0.0', 'community'),
('juniper', 'Juniper', 'networking', 'Juniper MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-juniper:1.0.0', 'community'),
('aruba', 'Aruba', 'networking', 'Aruba MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aruba:1.0.0', 'community'),
('ubiquiti', 'Ubiquiti', 'networking', 'Ubiquiti MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ubiquiti:1.0.0', 'community'),
('nginx-plus', 'Nginx Plus', 'networking', 'Nginx Plus MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-nginx-plus:1.0.0', 'community'),
('traefik', 'Traefik', 'networking', 'Traefik MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-traefik:1.0.0', 'community'),
('envoy', 'Envoy', 'networking', 'Envoy MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-envoy:1.0.0', 'community'),
('istio', 'Istio', 'networking', 'Istio MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-istio:1.0.0', 'community'),
('linkerd', 'Linkerd', 'networking', 'Linkerd MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-linkerd:1.0.0', 'community'),
('consul', 'Consul', 'networking', 'Consul MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-consul:1.0.0', 'community'),
('tailscale', 'Tailscale', 'networking', 'Tailscale MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tailscale:1.0.0', 'community'),
('wireguard', 'Wireguard', 'networking', 'Wireguard MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-wireguard:1.0.0', 'community'),
('vanta', 'Vanta', 'compliance', 'Vanta MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-vanta:1.0.0', 'community'),
('drata', 'Drata', 'compliance', 'Drata MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-drata:1.0.0', 'community'),
('secureframe', 'Secureframe', 'compliance', 'Secureframe MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-secureframe:1.0.0', 'community'),
('tugboat-logic', 'Tugboat Logic', 'compliance', 'Tugboat Logic MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tugboat-logic:1.0.0', 'community'),
('sprinto', 'Sprinto', 'compliance', 'Sprinto MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sprinto:1.0.0', 'community'),
('scrut-automation', 'Scrut Automation', 'compliance', 'Scrut Automation MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-scrut-automation:1.0.0', 'community'),
('scytale', 'Scytale', 'compliance', 'Scytale MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-scytale:1.0.0', 'community'),
('centraleyes', 'Centraleyes', 'compliance', 'Centraleyes MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-centraleyes:1.0.0', 'community'),
('hyperproof', 'Hyperproof', 'compliance', 'Hyperproof MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hyperproof:1.0.0', 'community'),
('anecdotes', 'Anecdotes', 'compliance', 'Anecdotes MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-anecdotes:1.0.0', 'community'),
('onspring', 'Onspring', 'compliance', 'Onspring MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-onspring:1.0.0', 'community'),
('reciprocity', 'Reciprocity', 'compliance', 'Reciprocity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-reciprocity:1.0.0', 'community'),
('laika', 'Laika', 'compliance', 'Laika MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-laika:1.0.0', 'community'),
('conveyor', 'Conveyor', 'compliance', 'Conveyor MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-conveyor:1.0.0', 'community'),
('auditboard', 'Auditboard', 'compliance', 'Auditboard MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-auditboard:1.0.0', 'community'),
('workiva', 'Workiva', 'compliance', 'Workiva MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-workiva:1.0.0', 'community'),
('navex', 'Navex', 'compliance', 'Navex MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-navex:1.0.0', 'community'),
('archer', 'Archer', 'compliance', 'Archer MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-archer:1.0.0', 'community'),
('openai', 'Openai', 'ai', 'Openai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-openai:1.0.0', 'community'),
('anthropic', 'Anthropic', 'ai', 'Anthropic MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-anthropic:1.0.0', 'community'),
('hugging-face', 'Hugging Face', 'ai', 'Hugging Face MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hugging-face:1.0.0', 'community'),
('aws-sagemaker', 'Aws Sagemaker', 'ai', 'Aws Sagemaker MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-sagemaker:1.0.0', 'community'),
('vertex-ai', 'Vertex Ai', 'ai', 'Vertex Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-vertex-ai:1.0.0', 'community'),
('azure-openai', 'Azure Openai', 'ai', 'Azure Openai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-openai:1.0.0', 'community'),
('cohere', 'Cohere', 'ai', 'Cohere MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cohere:1.0.0', 'community'),
('mistral', 'Mistral', 'ai', 'Mistral MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mistral:1.0.0', 'community'),
('replicate', 'Replicate', 'ai', 'Replicate MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-replicate:1.0.0', 'community'),
('together-ai', 'Together Ai', 'ai', 'Together Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-together-ai:1.0.0', 'community'),
('anyscale', 'Anyscale', 'ai', 'Anyscale MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-anyscale:1.0.0', 'community'),
('modal-com', 'Modal Com', 'ai', 'Modal Com MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-modal-com:1.0.0', 'community'),
('fireworks-ai', 'Fireworks Ai', 'ai', 'Fireworks Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-fireworks-ai:1.0.0', 'community'),
('deepinfra', 'Deepinfra', 'ai', 'Deepinfra MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-deepinfra:1.0.0', 'community'),
('perplexity', 'Perplexity', 'ai', 'Perplexity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-perplexity:1.0.0', 'community'),
('groq', 'Groq', 'ai', 'Groq MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-groq:1.0.0', 'community'),
('cerebras', 'Cerebras', 'ai', 'Cerebras MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cerebras:1.0.0', 'community'),
('sambanova', 'Sambanova', 'ai', 'Sambanova MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sambanova:1.0.0', 'community'),
('nvidia-nim', 'Nvidia Nim', 'ai', 'Nvidia Nim MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-nvidia-nim:1.0.0', 'community'),
('aws-bedrock', 'Aws Bedrock', 'ai', 'Aws Bedrock MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-bedrock:1.0.0', 'community'),
('palm-api', 'Palm Api', 'ai', 'Palm Api MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-palm-api:1.0.0', 'community'),
('llama-cloud', 'Llama Cloud', 'ai', 'Llama Cloud MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-llama-cloud:1.0.0', 'community'),
('stability-ai', 'Stability Ai', 'ai', 'Stability Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-stability-ai:1.0.0', 'community'),
('midjourney', 'Midjourney', 'ai', 'Midjourney MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-midjourney:1.0.0', 'community'),
('dall-e', 'Dall E', 'ai', 'Dall E MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-dall-e:1.0.0', 'community'),
('runway-ml', 'Runway Ml', 'ai', 'Runway Ml MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-runway-ml:1.0.0', 'community'),
('jasper-ai', 'Jasper Ai', 'ai', 'Jasper Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-jasper-ai:1.0.0', 'community'),
('writer-ai', 'Writer Ai', 'ai', 'Writer Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-writer-ai:1.0.0', 'community'),
('copy-ai', 'Copy Ai', 'ai', 'Copy Ai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-copy-ai:1.0.0', 'community'),
('twilio', 'Twilio', 'communication', 'Twilio MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-twilio:1.0.0', 'community'),
('sendgrid', 'Sendgrid', 'communication', 'Sendgrid MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sendgrid:1.0.0', 'community'),
('mailgun', 'Mailgun', 'communication', 'Mailgun MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mailgun:1.0.0', 'community'),
('pagerduty', 'Pagerduty', 'communication', 'Pagerduty MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-pagerduty:1.0.0', 'community'),
('opsgenie', 'Opsgenie', 'communication', 'Opsgenie MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-opsgenie:1.0.0', 'community'),
('victorops', 'Victorops', 'communication', 'Victorops MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-victorops:1.0.0', 'community'),
('xmatters', 'Xmatters', 'communication', 'Xmatters MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-xmatters:1.0.0', 'community'),
('statuspage', 'Statuspage', 'communication', 'Statuspage MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-statuspage:1.0.0', 'community'),
('atlassian-statuspage', 'Atlassian Statuspage', 'communication', 'Atlassian Statuspage MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-atlassian-statuspage:1.0.0', 'community'),
('betteruptime', 'Betteruptime', 'communication', 'Betteruptime MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-betteruptime:1.0.0', 'community'),
('incident-io', 'Incident Io', 'communication', 'Incident Io MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-incident-io:1.0.0', 'community'),
('firehydrant', 'Firehydrant', 'communication', 'Firehydrant MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-firehydrant:1.0.0', 'community'),
('rootly', 'Rootly', 'communication', 'Rootly MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-rootly:1.0.0', 'community'),
('blameless', 'Blameless', 'communication', 'Blameless MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-blameless:1.0.0', 'community'),
('jeli', 'Jeli', 'communication', 'Jeli MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-jeli:1.0.0', 'community'),
('shoreline', 'Shoreline', 'communication', 'Shoreline MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-shoreline:1.0.0', 'community'),
('zoom', 'Zoom', 'communication', 'Zoom MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zoom:1.0.0', 'community'),
('ringcentral', 'Ringcentral', 'communication', 'Ringcentral MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ringcentral:1.0.0', 'community'),
('vonage', 'Vonage', 'communication', 'Vonage MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-vonage:1.0.0', 'community'),
('plivo', 'Plivo', 'communication', 'Plivo MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-plivo:1.0.0', 'community'),
('messagebird', 'Messagebird', 'communication', 'Messagebird MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-messagebird:1.0.0', 'community'),
('bandwidth', 'Bandwidth', 'communication', 'Bandwidth MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bandwidth:1.0.0', 'community'),
('telnyx', 'Telnyx', 'communication', 'Telnyx MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-telnyx:1.0.0', 'community'),
('aws-s3', 'Aws S3', 'storage', 'Aws S3 MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-s3:1.0.0', 'community'),
('gcs', 'Gcs', 'storage', 'Gcs MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcs:1.0.0', 'community'),
('azure-blob', 'Azure Blob', 'storage', 'Azure Blob MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-blob:1.0.0', 'community'),
('backblaze', 'Backblaze', 'storage', 'Backblaze MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-backblaze:1.0.0', 'community'),
('wasabi', 'Wasabi', 'storage', 'Wasabi MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-wasabi:1.0.0', 'community'),
('cloudinary', 'Cloudinary', 'storage', 'Cloudinary MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cloudinary:1.0.0', 'community'),
('imgix', 'Imgix', 'storage', 'Imgix MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-imgix:1.0.0', 'community'),
('minio', 'Minio', 'storage', 'Minio MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-minio:1.0.0', 'community'),
('ceph', 'Ceph', 'storage', 'Ceph MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ceph:1.0.0', 'community'),
('storj', 'Storj', 'storage', 'Storj MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-storj:1.0.0', 'community'),
('filecoin', 'Filecoin', 'storage', 'Filecoin MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-filecoin:1.0.0', 'community'),
('arweave', 'Arweave', 'storage', 'Arweave MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-arweave:1.0.0', 'community'),
('ipfs', 'Ipfs', 'storage', 'Ipfs MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ipfs:1.0.0', 'community'),
('r2-cloudflare', 'R2 Cloudflare', 'storage', 'R2 Cloudflare MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-r2-cloudflare:1.0.0', 'community'),
('bunny-cdn', 'Bunny Cdn', 'storage', 'Bunny Cdn MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bunny-cdn:1.0.0', 'community'),
('docker-hub', 'Docker Hub', 'container', 'Docker Hub MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-docker-hub:1.0.0', 'community'),
('harbor', 'Harbor', 'container', 'Harbor MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-harbor:1.0.0', 'community'),
('aws-ecr', 'Aws Ecr', 'container', 'Aws Ecr MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-ecr:1.0.0', 'community'),
('gcr', 'Gcr', 'container', 'Gcr MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcr:1.0.0', 'community'),
('azure-acr', 'Azure Acr', 'container', 'Azure Acr MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-acr:1.0.0', 'community'),
('quay-io', 'Quay Io', 'container', 'Quay Io MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-quay-io:1.0.0', 'community'),
('aws-eks', 'Aws Eks', 'container', 'Aws Eks MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-eks:1.0.0', 'community'),
('gcp-gke', 'Gcp Gke', 'container', 'Gcp Gke MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-gke:1.0.0', 'community'),
('azure-aks', 'Azure Aks', 'container', 'Azure Aks MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-aks:1.0.0', 'community'),
('rancher', 'Rancher', 'container', 'Rancher MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-rancher:1.0.0', 'community'),
('k3s', 'K3s', 'container', 'K3s MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-k3s:1.0.0', 'community'),
('kind', 'Kind', 'container', 'Kind MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-kind:1.0.0', 'community'),
('minikube', 'Minikube', 'container', 'Minikube MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-minikube:1.0.0', 'community'),
('openshift', 'Openshift', 'container', 'Openshift MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-openshift:1.0.0', 'community'),
('tanzu', 'Tanzu', 'container', 'Tanzu MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tanzu:1.0.0', 'community'),
('nomad-cluster', 'Nomad Cluster', 'container', 'Nomad Cluster MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-nomad-cluster:1.0.0', 'community'),
('portainer', 'Portainer', 'container', 'Portainer MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-portainer:1.0.0', 'community'),
('lens', 'Lens', 'container', 'Lens MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-lens:1.0.0', 'community'),
('zapier', 'Zapier', 'apigateway', 'Zapier MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zapier:1.0.0', 'community'),
('mulesoft', 'Mulesoft', 'apigateway', 'Mulesoft MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mulesoft:1.0.0', 'community'),
('workato', 'Workato', 'apigateway', 'Workato MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-workato:1.0.0', 'community'),
('tray-io', 'Tray Io', 'apigateway', 'Tray Io MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tray-io:1.0.0', 'community'),
('n8n', 'N8n', 'apigateway', 'N8n MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-n8n:1.0.0', 'community'),
('make-com', 'Make Com', 'apigateway', 'Make Com MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-make-com:1.0.0', 'community'),
('apigee', 'Apigee', 'apigateway', 'Apigee MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-apigee:1.0.0', 'community'),
('kong', 'Kong', 'apigateway', 'Kong MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-kong:1.0.0', 'community'),
('aws-api-gateway', 'Aws Api Gateway', 'apigateway', 'Aws Api Gateway MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-api-gateway:1.0.0', 'community'),
('azure-apim', 'Azure Apim', 'apigateway', 'Azure Apim MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-apim:1.0.0', 'community'),
('gcp-api-gateway', 'Gcp Api Gateway', 'apigateway', 'Gcp Api Gateway MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-api-gateway:1.0.0', 'community'),
('tyk', 'Tyk', 'apigateway', 'Tyk MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tyk:1.0.0', 'community'),
('gravitee', 'Gravitee', 'apigateway', 'Gravitee MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gravitee:1.0.0', 'community'),
('fusio', 'Fusio', 'apigateway', 'Fusio MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-fusio:1.0.0', 'community'),
('wso2', 'Wso2', 'apigateway', 'Wso2 MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-wso2:1.0.0', 'community'),
('3scale', '3scale', 'apigateway', '3scale MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-3scale:1.0.0', 'community'),
('workday', 'Workday', 'hr', 'Workday MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-workday:1.0.0', 'community'),
('bamboohr', 'Bamboohr', 'hr', 'Bamboohr MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bamboohr:1.0.0', 'community'),
('gusto', 'Gusto', 'hr', 'Gusto MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gusto:1.0.0', 'community'),
('rippling', 'Rippling', 'hr', 'Rippling MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-rippling:1.0.0', 'community'),
('deel', 'Deel', 'hr', 'Deel MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-deel:1.0.0', 'community'),
('remote-com', 'Remote Com', 'hr', 'Remote Com MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-remote-com:1.0.0', 'community'),
('oyster', 'Oyster', 'hr', 'Oyster MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-oyster:1.0.0', 'community'),
('papaya-global', 'Papaya Global', 'hr', 'Papaya Global MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-papaya-global:1.0.0', 'community'),
('justworks', 'Justworks', 'hr', 'Justworks MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-justworks:1.0.0', 'community'),
('paylocity', 'Paylocity', 'hr', 'Paylocity MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-paylocity:1.0.0', 'community'),
('paycom', 'Paycom', 'hr', 'Paycom MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-paycom:1.0.0', 'community'),
('adp', 'Adp', 'hr', 'Adp MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-adp:1.0.0', 'community'),
('ultipro', 'Ultipro', 'hr', 'Ultipro MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ultipro:1.0.0', 'community'),
('hibob', 'Hibob', 'hr', 'Hibob MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hibob:1.0.0', 'community'),
('personio', 'Personio', 'hr', 'Personio MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-personio:1.0.0', 'community'),
('humaans', 'Humaans', 'hr', 'Humaans MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-humaans:1.0.0', 'community'),
('brex', 'Brex', 'hr', 'Brex MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-brex:1.0.0', 'community'),
('stripe', 'Stripe', 'hr', 'Stripe MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-stripe:1.0.0', 'community'),
('square', 'Square', 'hr', 'Square MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-square:1.0.0', 'community'),
('adyen', 'Adyen', 'hr', 'Adyen MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-adyen:1.0.0', 'community'),
('salesforce', 'Salesforce', 'crm', 'Salesforce MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-salesforce:1.0.0', 'community'),
('hubspot', 'Hubspot', 'crm', 'Hubspot MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hubspot:1.0.0', 'community'),
('zoho-crm', 'Zoho Crm', 'crm', 'Zoho Crm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zoho-crm:1.0.0', 'community'),
('pipedrive', 'Pipedrive', 'crm', 'Pipedrive MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-pipedrive:1.0.0', 'community'),
('freshsales', 'Freshsales', 'crm', 'Freshsales MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-freshsales:1.0.0', 'community'),
('close-crm', 'Close Crm', 'crm', 'Close Crm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-close-crm:1.0.0', 'community'),
('copper-crm', 'Copper Crm', 'crm', 'Copper Crm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-copper-crm:1.0.0', 'community'),
('insightly', 'Insightly', 'crm', 'Insightly MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-insightly:1.0.0', 'community'),
('nutshell', 'Nutshell', 'crm', 'Nutshell MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-nutshell:1.0.0', 'community'),
('agile-crm', 'Agile Crm', 'crm', 'Agile Crm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-agile-crm:1.0.0', 'community'),
('less-annoying', 'Less Annoying', 'crm', 'Less Annoying MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-less-annoying:1.0.0', 'community'),
('sugarcrm', 'Sugarcrm', 'crm', 'Sugarcrm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-sugarcrm:1.0.0', 'community'),
('vtiger', 'Vtiger', 'crm', 'Vtiger MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-vtiger:1.0.0', 'community'),
('capsule-crm', 'Capsule Crm', 'crm', 'Capsule Crm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-capsule-crm:1.0.0', 'community'),
('zendesk', 'Zendesk', 'crm', 'Zendesk MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zendesk:1.0.0', 'community'),
('freshdesk', 'Freshdesk', 'crm', 'Freshdesk MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-freshdesk:1.0.0', 'community'),
('intercom', 'Intercom', 'crm', 'Intercom MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-intercom:1.0.0', 'community'),
('drift', 'Drift', 'crm', 'Drift MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-drift:1.0.0', 'community'),
('crisp', 'Crisp', 'crm', 'Crisp MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-crisp:1.0.0', 'community'),
('helpscout', 'Helpscout', 'crm', 'Helpscout MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-helpscout:1.0.0', 'community'),
('epic-fhir', 'Epic Fhir', 'healthcare', 'Epic Fhir MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-epic-fhir:1.0.0', 'community'),
('cerner-fhir', 'Cerner Fhir', 'healthcare', 'Cerner Fhir MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cerner-fhir:1.0.0', 'community'),
('allscripts', 'Allscripts', 'healthcare', 'Allscripts MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-allscripts:1.0.0', 'community'),
('meditech', 'Meditech', 'healthcare', 'Meditech MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-meditech:1.0.0', 'community'),
('eclinicalworks', 'Eclinicalworks', 'healthcare', 'Eclinicalworks MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-eclinicalworks:1.0.0', 'community'),
('athenahealth', 'Athenahealth', 'healthcare', 'Athenahealth MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-athenahealth:1.0.0', 'community'),
('nextgen', 'Nextgen', 'healthcare', 'Nextgen MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-nextgen:1.0.0', 'community'),
('kareo', 'Kareo', 'healthcare', 'Kareo MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-kareo:1.0.0', 'community'),
('drchrono', 'Drchrono', 'healthcare', 'Drchrono MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-drchrono:1.0.0', 'community'),
('practice-fusion', 'Practice Fusion', 'healthcare', 'Practice Fusion MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-practice-fusion:1.0.0', 'community'),
('veradigm', 'Veradigm', 'healthcare', 'Veradigm MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-veradigm:1.0.0', 'community'),
('modernizing-medicine', 'Modernizing Medicine', 'healthcare', 'Modernizing Medicine MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-modernizing-medicine:1.0.0', 'community'),
('elation', 'Elation', 'healthcare', 'Elation MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-elation:1.0.0', 'community'),
('greenway', 'Greenway', 'healthcare', 'Greenway MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-greenway:1.0.0', 'community'),
('health-gorilla', 'Health Gorilla', 'healthcare', 'Health Gorilla MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-health-gorilla:1.0.0', 'community'),
('redox-health', 'Redox Health', 'healthcare', 'Redox Health MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-redox-health:1.0.0', 'community'),
('datica', 'Datica', 'healthcare', 'Datica MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-datica:1.0.0', 'community'),
('particle-health', 'Particle Health', 'healthcare', 'Particle Health MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-particle-health:1.0.0', 'community'),
('clio', 'Clio', 'legal', 'Clio MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-clio:1.0.0', 'community'),
('litify', 'Litify', 'legal', 'Litify MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-litify:1.0.0', 'community'),
('smokeball', 'Smokeball', 'legal', 'Smokeball MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-smokeball:1.0.0', 'community'),
('lawcus', 'Lawcus', 'legal', 'Lawcus MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-lawcus:1.0.0', 'community'),
('practicepanther', 'Practicepanther', 'legal', 'Practicepanther MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-practicepanther:1.0.0', 'community'),
('mycase', 'Mycase', 'legal', 'Mycase MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mycase:1.0.0', 'community'),
('rocketmatter', 'Rocketmatter', 'legal', 'Rocketmatter MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-rocketmatter:1.0.0', 'community'),
('filevine', 'Filevine', 'legal', 'Filevine MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-filevine:1.0.0', 'community'),
('neos', 'Neos', 'legal', 'Neos MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-neos:1.0.0', 'community'),
('assembly-legal', 'Assembly Legal', 'legal', 'Assembly Legal MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-assembly-legal:1.0.0', 'community'),
('contractpodai', 'Contractpodai', 'legal', 'Contractpodai MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-contractpodai:1.0.0', 'community'),
('ironclad-legal', 'Ironclad Legal', 'legal', 'Ironclad Legal MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ironclad-legal:1.0.0', 'community'),
('juro', 'Juro', 'legal', 'Juro MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-juro:1.0.0', 'community'),
('evisort', 'Evisort', 'legal', 'Evisort MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-evisort:1.0.0', 'community'),
('steam-api', 'Steam Api', 'gaming', 'Steam Api MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-steam-api:1.0.0', 'community'),
('epic-games', 'Epic Games', 'gaming', 'Epic Games MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-epic-games:1.0.0', 'community'),
('xbox-live', 'Xbox Live', 'gaming', 'Xbox Live MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-xbox-live:1.0.0', 'community'),
('playstation-network', 'Playstation Network', 'gaming', 'Playstation Network MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-playstation-network:1.0.0', 'community'),
('unity-gaming', 'Unity Gaming', 'gaming', 'Unity Gaming MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-unity-gaming:1.0.0', 'community'),
('unreal-engine', 'Unreal Engine', 'gaming', 'Unreal Engine MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-unreal-engine:1.0.0', 'community'),
('roblox-api', 'Roblox Api', 'gaming', 'Roblox Api MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-roblox-api:1.0.0', 'community'),
('twitch-api', 'Twitch Api', 'gaming', 'Twitch Api MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-twitch-api:1.0.0', 'community'),
('discord-bot', 'Discord Bot', 'gaming', 'Discord Bot MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-discord-bot:1.0.0', 'community'),
('youtube-gaming', 'Youtube Gaming', 'gaming', 'Youtube Gaming MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-youtube-gaming:1.0.0', 'community'),
('aws-iot-core', 'Aws Iot Core', 'iot', 'Aws Iot Core MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-iot-core:1.0.0', 'community'),
('azure-iot', 'Azure Iot', 'iot', 'Azure Iot MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-iot:1.0.0', 'community'),
('gcp-iot', 'Gcp Iot', 'iot', 'Gcp Iot MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-iot:1.0.0', 'community'),
('particle-io', 'Particle Io', 'iot', 'Particle Io MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-particle-io:1.0.0', 'community'),
('arduino-cloud', 'Arduino Cloud', 'iot', 'Arduino Cloud MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-arduino-cloud:1.0.0', 'community'),
('balena', 'Balena', 'iot', 'Balena MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-balena:1.0.0', 'community'),
('losant', 'Losant', 'iot', 'Losant MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-losant:1.0.0', 'community'),
('datacake', 'Datacake', 'iot', 'Datacake MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-datacake:1.0.0', 'community'),
('thingsboard', 'Thingsboard', 'iot', 'Thingsboard MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-thingsboard:1.0.0', 'community'),
('canvas', 'Canvas', 'education', 'Canvas MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-canvas:1.0.0', 'community'),
('blackboard', 'Blackboard', 'education', 'Blackboard MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-blackboard:1.0.0', 'community'),
('moodle', 'Moodle', 'education', 'Moodle MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-moodle:1.0.0', 'community'),
('brightspace', 'Brightspace', 'education', 'Brightspace MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-brightspace:1.0.0', 'community'),
('schoology', 'Schoology', 'education', 'Schoology MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-schoology:1.0.0', 'community'),
('google-classroom', 'Google Classroom', 'education', 'Google Classroom MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-google-classroom:1.0.0', 'community'),
('clever', 'Clever', 'education', 'Clever MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-clever:1.0.0', 'community'),
('classlink', 'Classlink', 'education', 'Classlink MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-classlink:1.0.0', 'community'),
('powerschool', 'Powerschool', 'education', 'Powerschool MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-powerschool:1.0.0', 'community'),
('infinite-campus', 'Infinite Campus', 'education', 'Infinite Campus MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-infinite-campus:1.0.0', 'community'),
('shopify', 'Shopify', 'ecommerce', 'Shopify MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-shopify:1.0.0', 'community'),
('woocommerce', 'Woocommerce', 'ecommerce', 'Woocommerce MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-woocommerce:1.0.0', 'community'),
('magento', 'Magento', 'ecommerce', 'Magento MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-magento:1.0.0', 'community'),
('bigcommerce', 'Bigcommerce', 'ecommerce', 'Bigcommerce MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bigcommerce:1.0.0', 'community'),
('squarespace-commerce', 'Squarespace Commerce', 'ecommerce', 'Squarespace Commerce MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-squarespace-commerce:1.0.0', 'community'),
('stripe-commerce', 'Stripe Commerce', 'ecommerce', 'Stripe Commerce MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-stripe-commerce:1.0.0', 'community'),
('paypal-commerce', 'Paypal Commerce', 'ecommerce', 'Paypal Commerce MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-paypal-commerce:1.0.0', 'community'),
('amazon-seller', 'Amazon Seller', 'ecommerce', 'Amazon Seller MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-amazon-seller:1.0.0', 'community'),
('ebay-api', 'Ebay Api', 'ecommerce', 'Ebay Api MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-ebay-api:1.0.0', 'community'),
('etsy-api', 'Etsy Api', 'ecommerce', 'Etsy Api MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-etsy-api:1.0.0', 'community'),
('google-analytics', 'Google Analytics', 'analytics', 'Google Analytics MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-google-analytics:1.0.0', 'community'),
('mixpanel', 'Mixpanel', 'analytics', 'Mixpanel MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-mixpanel:1.0.0', 'community'),
('amplitude', 'Amplitude', 'analytics', 'Amplitude MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-amplitude:1.0.0', 'community'),
('segment', 'Segment', 'analytics', 'Segment MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-segment:1.0.0', 'community'),
('rudderstack', 'Rudderstack', 'analytics', 'Rudderstack MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-rudderstack:1.0.0', 'community'),
('snowplow', 'Snowplow', 'analytics', 'Snowplow MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-snowplow:1.0.0', 'community'),
('heap', 'Heap', 'analytics', 'Heap MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-heap:1.0.0', 'community'),
('fullstory', 'Fullstory', 'analytics', 'Fullstory MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-fullstory:1.0.0', 'community'),
('hotjar', 'Hotjar', 'analytics', 'Hotjar MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hotjar:1.0.0', 'community'),
('logrocket', 'Logrocket', 'analytics', 'Logrocket MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-logrocket:1.0.0', 'community'),
('posthog', 'Posthog', 'analytics', 'Posthog MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-posthog:1.0.0', 'community'),
('matomo', 'Matomo', 'analytics', 'Matomo MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-matomo:1.0.0', 'community'),
('plausible', 'Plausible', 'analytics', 'Plausible MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-plausible:1.0.0', 'community'),
('hashicorp-vault', 'Hashicorp Vault', 'secrets', 'Hashicorp Vault MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-hashicorp-vault:1.0.0', 'community'),
('aws-secrets-manager', 'Aws Secrets Manager', 'secrets', 'Aws Secrets Manager MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-aws-secrets-manager:1.0.0', 'community'),
('gcp-secret-manager', 'Gcp Secret Manager', 'secrets', 'Gcp Secret Manager MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-gcp-secret-manager:1.0.0', 'community'),
('azure-key-vault', 'Azure Key Vault', 'secrets', 'Azure Key Vault MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-azure-key-vault:1.0.0', 'community'),
('cyberark-conjur', 'Cyberark Conjur', 'secrets', 'Cyberark Conjur MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-cyberark-conjur:1.0.0', 'community'),
('doppler', 'Doppler', 'secrets', 'Doppler MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-doppler:1.0.0', 'community'),
('infisical', 'Infisical', 'secrets', 'Infisical MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-infisical:1.0.0', 'community'),
('1password-connect', '1password Connect', 'secrets', '1password Connect MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-1password-connect:1.0.0', 'community'),
('bitwarden-secrets', 'Bitwarden Secrets', 'secrets', 'Bitwarden Secrets MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-bitwarden-secrets:1.0.0', 'community'),
('akeyless', 'Akeyless', 'secrets', 'Akeyless MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-akeyless:1.0.0', 'community'),
('thales-ciphertrust', 'Thales Ciphertrust', 'secrets', 'Thales Ciphertrust MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-thales-ciphertrust:1.0.0', 'community'),
('collibra', 'Collibra', 'governance', 'Collibra MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-collibra:1.0.0', 'community'),
('alation', 'Alation', 'governance', 'Alation MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-alation:1.0.0', 'community'),
('atlan', 'Atlan', 'governance', 'Atlan MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-atlan:1.0.0', 'community'),
('informatica', 'Informatica', 'governance', 'Informatica MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-informatica:1.0.0', 'community'),
('talend', 'Talend', 'governance', 'Talend MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-talend:1.0.0', 'community'),
('datahub', 'Datahub', 'governance', 'Datahub MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-datahub:1.0.0', 'community'),
('amundsen', 'Amundsen', 'governance', 'Amundsen MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-amundsen:1.0.0', 'community'),
('openmetadata', 'Openmetadata', 'governance', 'Openmetadata MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-openmetadata:1.0.0', 'community'),
('apache-atlas', 'Apache Atlas', 'governance', 'Apache Atlas MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-apache-atlas:1.0.0', 'community'),
('prometheus', 'Prometheus', 'observability', 'Prometheus MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-prometheus:1.0.0', 'community'),
('grafana', 'Grafana', 'observability', 'Grafana MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-grafana:1.0.0', 'community'),
('new-relic', 'New Relic', 'observability', 'New Relic MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-new-relic:1.0.0', 'community'),
('dynatrace', 'Dynatrace', 'observability', 'Dynatrace MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-dynatrace:1.0.0', 'community'),
('appdynamics', 'Appdynamics', 'observability', 'Appdynamics MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-appdynamics:1.0.0', 'community'),
('lightstep', 'Lightstep', 'observability', 'Lightstep MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-lightstep:1.0.0', 'community'),
('honeycomb', 'Honeycomb', 'observability', 'Honeycomb MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-honeycomb:1.0.0', 'community'),
('jaeger', 'Jaeger', 'observability', 'Jaeger MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-jaeger:1.0.0', 'community'),
('zipkin', 'Zipkin', 'observability', 'Zipkin MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-zipkin:1.0.0', 'community'),
('tempo', 'Tempo', 'observability', 'Tempo MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-tempo:1.0.0', 'community'),
('signoz', 'Signoz', 'observability', 'Signoz MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-signoz:1.0.0', 'community'),
('uptrace', 'Uptrace', 'observability', 'Uptrace MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-uptrace:1.0.0', 'community'),
('groundcover', 'Groundcover', 'observability', 'Groundcover MCP integration for RuntimeAI governance', 'runtimeai/mcp-server-groundcover:1.0.0', 'community')
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    mcp_server_image = EXCLUDED.mcp_server_image,
    updated_at = NOW();

-- Total servers: 492
